# Dockerfile.frontend
FROM node:20-alpine

WORKDIR /app

# Instala dependências
COPY package*.json ./
RUN npm install

# Copia o restante do código
COPY . .

# Expõe porta padrão do Next.js
EXPOSE 3000

# Rodar o Next.js em dev mode com hot reload
CMD ["npm", "run", "dev"]