"""alterar quantidade dos itens do ajeum

Revision ID: 0024
Revises: 0023_enable_pg_trgm_extension
Create Date: 2026-09-05 15:20:46.225813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0024'
down_revision: Union[str, None] = '0023_enable_pg_trgm_extension'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ajeum', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('ajeum', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.add_column('ajeum_item', sa.Column('quantidade_necessaria', sa.Numeric(precision=12, scale=3), nullable=False))
    op.add_column('ajeum_item', sa.Column('unidade', sa.String(length=20), nullable=False))
    op.alter_column('ajeum_item', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('ajeum_item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_column('ajeum_item', 'limite')
    op.add_column('ajeum_selecao', sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False))
    op.alter_column('ajeum_selecao', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ajeum_selecao', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ajeum_selecao', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('ajeum_selecao', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('ajeum_selecao', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('ajeum_selecao', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('ajeum_selecao', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('ajeum_selecao', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'selecionado'::character varying"),
               existing_nullable=False)
    op.drop_column('ajeum_selecao', 'quantidade')
    op.add_column('ajeum_item', sa.Column('limite', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('ajeum_item', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('ajeum_item', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('ajeum_item', 'unidade')
    op.drop_column('ajeum_item', 'quantidade_necessaria')
    op.alter_column('ajeum', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('ajeum', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
