"""initial

Revision ID: 11b4a64b5a9d
Revises: 
Create Date: 2026-03-11 17:26:08.410789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b4a64b5a9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

    
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint'),
    schema='axeflow'
    )
    op.create_table('terreiros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='axeflow'
    )
    op.create_table('consulentes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('terreiro_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('primeira_visita', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['terreiro_id'], ['axeflow.terreiros.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('terreiro_id', 'telefone'),
    schema='axeflow'
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('terreiro_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['terreiro_id'], ['axeflow.terreiros.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='axeflow'
    )
    op.create_table('giras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('terreiro_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('limite_consulentes', sa.Integer(), nullable=False),
    sa.Column('abertura_lista', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fechamento_lista', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responsavel_lista_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('acesso', sa.String(length=20), nullable=True),
    sa.Column('slug_publico', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['responsavel_lista_id'], ['axeflow.usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['terreiro_id'], ['axeflow.terreiros.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug_publico'),
    schema='axeflow'
    )
    op.create_index('ix_giras_terreiro_data', 'giras', ['terreiro_id', 'data'], unique=False, schema='axeflow')
    op.create_table('inscricoes_gira',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gira_id', sa.UUID(), nullable=False),
    sa.Column('consulente_id', sa.UUID(), nullable=True),
    sa.Column('membro_id', sa.UUID(), nullable=True),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('confirmado', 'lista_espera', 'compareceu', 'faltou', 'cancelado', name='status_inscricao_enum', create_constraint=True), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consulente_id'], ['axeflow.consulentes.id'], ),
    sa.ForeignKeyConstraint(['gira_id'], ['axeflow.giras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membro_id'], ['axeflow.usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gira_id', 'consulente_id', name='uq_gira_consulente'),
    schema='axeflow'
    )
    op.create_index('ix_inscricoes_gira_posicao', 'inscricoes_gira', ['gira_id', 'posicao'], unique=False, schema='axeflow')
    op.create_index('ix_inscricoes_gira_status', 'inscricoes_gira', ['gira_id', 'status'], unique=False, schema='axeflow')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inscricoes_gira_status', table_name='inscricoes_gira', schema='axeflow')
    op.drop_index('ix_inscricoes_gira_posicao', table_name='inscricoes_gira', schema='axeflow')
    op.drop_table('inscricoes_gira', schema='axeflow')
    op.drop_index('ix_giras_terreiro_data', table_name='giras', schema='axeflow')
    op.drop_table('giras', schema='axeflow')
    op.drop_table('usuarios', schema='axeflow')
    op.drop_table('consulentes', schema='axeflow')
    op.drop_table('terreiros', schema='axeflow')
    op.drop_table('push_subscriptions', schema='axeflow')
    # ### end Alembic commands ###
