"""Add Coluna limite_membros

Revision ID: 7beb915f0351
Revises: 0003_melhorias
Create Date: 2026-03-12 00:57:49.128268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7beb915f0351'
down_revision: Union[str, None] = '0003_melhorias'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giras', sa.Column('limite_membros', sa.Integer(), nullable=True))
    op.alter_column('giras', 'limite_consulentes',
               existing_type=sa.INTEGER(),
               nullable=True)

     # Nota: a coluna status em inscricoes_gira é VARCHAR(50) — não um ENUM PostgreSQL.
    # O valor 'lista_espera' já é aceito sem nenhuma alteração de schema.
    
    op.drop_constraint('fk_inscricoes_gira_gira_id', 'inscricoes_gira', type_='foreignkey')
    op.create_foreign_key(None, 'inscricoes_gira', 'giras', ['gira_id'], ['id'])
    op.create_index(op.f('ix_push_subscriptions_endpoint'), 'push_subscriptions', ['endpoint'], unique=True)
    op.drop_constraint('push_subscriptions_terreiro_id_fkey', 'push_subscriptions', type_='foreignkey')
    op.drop_column('push_subscriptions', 'terreiro_id')
    op.alter_column('terreiros', 'cidade',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('terreiros_slug_key', 'terreiros', type_='unique')
    op.drop_column('terreiros', 'slug')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('terreiros', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('terreiros_slug_key', 'terreiros', ['slug'])
    op.alter_column('terreiros', 'cidade',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('push_subscriptions', sa.Column('terreiro_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('push_subscriptions_terreiro_id_fkey', 'push_subscriptions', 'terreiros', ['terreiro_id'], ['id'])
    op.drop_index(op.f('ix_push_subscriptions_endpoint'), table_name='push_subscriptions')
    op.drop_column('push_subscriptions', 'updated_at')
    op.drop_constraint(None, 'inscricoes_gira', type_='foreignkey')
    op.create_foreign_key('fk_inscricoes_gira_gira_id', 'inscricoes_gira', 'giras', ['gira_id'], ['id'], ondelete='CASCADE')
     # Nota: a coluna status em inscricoes_gira é VARCHAR(50) — não um ENUM PostgreSQL.
    # O valor 'lista_espera' já é aceito sem nenhuma alteração de schema.
    op.alter_column('giras', 'acesso',
               existing_type=sa.Enum('publica', 'fechada', name='acessogiraenum'),
               type_=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'publica'::character varying"))
    
    op.alter_column('giras', 'limite_consulentes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('giras', 'limite_membros')
    # ### end Alembic commands ###
