name: Keep Render Awake

on:
  schedule:
    # A cada 5 minutos
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Show date
        run: date
    
      - name: Ping Render
        run: |
          curl --fail --silent --show-error \
            https://axeflow-backend.onrender.com/health
